config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
	get		'results/create'
	root	'static_pages#home'
	get		'/help',	to:	'static_pages#help'
	get		'/about',	to:	'static_pages#about'
	get		'/contact',	to:	'static_pages#contact'
	get		'/signup',	to:	'users#new'
	post	'/signup',	to:	'users#create'
	get		'/login',	to:	'sessions#new'
	post	'/login',	to:	'sessions#create'
	delete	'/logout',	to:	'sessions#destroy'
	post	'/result',	to:	'results#create'
	post	'/judged',	to:	'submissions#update'
	get		'submissions/renew',	to:	'submissions#renew'
	get		'submissions/srenew',	to:	'submissions#srenew'
	get		'submissions/getall',	to:	'submissions#getall'
	get		'problems/getnames',	to:	'problems#getnames'
	get		'users/getnames',		to:	'users#getnames'
	get		'users/getall',			to:	'users#getall'
	get		'problems/getall',		to:	'problems#getall'
	mathjax 'mathjax'
	resources :users
	resources :problems
	resources :submissions
	mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save {email.downcase!}
	has_many :accepteds
	has_many :submissions
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
		format: {with: VALID_EMAIL_REGEX},
		uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum:6}, allow_nil: true

	# 渡された文字列のハッシュ値を返す
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST
													: BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# ランダムな22文字のトークンを返す
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# 永続セッションのためにユーザーをデータベースに記憶する
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# 渡されたトークンがダイジェストと一致したらtrueを返す
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# ユーザーのログイン情報を破棄する
	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: :destroy

	def getnames
		users = User.all
		data = []
		users.each{|u|
			data.push(u.name)
		}
		result = []
		data.sort.each{|n|
			result.push({
				'id': n,
				'text': n
			})
		}
		render json: result
	end

	def getall
		users = User.all
		data = []
		users.each{|u|
			data.push({
				'user_name': u.name,
				'user_id': u.id,
				'point': u.point,
				'solved': u.solved,
				'submitted': u.submitted,
				'created_at': view_context.simple_time(u.created_at)
			})
		}
		render json: data
	end

	def index
		@users = Kaminari.paginate_array(User.all.sort_by{|u| -u.point}).page(params[:page]).per(20)
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			# 即ログインする
			log_in @user
			# flashを表示
			flash[:success] = "ようこそ！"
			# redirect_to user_url(@user) と等価
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "更新されました"
			redirect_to @user
		else
			# 失敗したら編集ページをレンダリング
			render 'edit'
		end
	end

	def destroy
		deleted_user = User.find(params[:id])
		deleted_user_name = deleted_user.name
		deleted_user.destroy
		flash[:success] = "${deleted_user_name}を削除完了"
		redirect_to users_url
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		# beforeアクション

		# ログイン済みユーザーであるか確認
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in."
				redirect_to login_url
			end
		end

		# 正しいユーザーであるか確認
		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
	<%= render 'shared/error_messages', object: @user %>

	<%= f.label '名前' %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label 'メールアドレス' %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label 'パスワード' %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label 'パスワード確認' %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit yield(:button_text), class: 'btn btn-primary col-md-4 col-md-offset-4' %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "削除", user, method: :delete,
									data: { confirm: "いいのか？" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, '設定') %>
<% provide(:url, user_path) %>
<% provide(:button_text, '保存') %>
<h1>設定</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target="_blank">アイコンを変更(gravatar)</a>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ランキング') %>
<h1>ランキング</h1>

<div id='users_table'>
	<v-client-table :columns='columns' :data='data' :options='options'>
		<a slot='user_name' slot-scope='props' :href='`/users/${props.row.user_id}`'>
			{{props.row.user_name}}
		</a>
	</v-client-table>
</div>


<% if false %>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th class="col-xs-2">ユーザー名</th>
			<th class="col-xs-2">合計得点</th>
			<th class="col-xs-2">解いた問題数</th>
			<th class="col-xs-2">提出回数</th>
			<th class="col-xs-2">登録日時</th>
			<% if current_user.admin? %>
				<th class="col-xs-1">管理</th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |u| %>
			<tr>
				<td><%= link_to u.name, u %></td>
				<td><%= u.point %></td>
				<td><%= u.solved %></td>
				<td><%= u.submitted %></td>
				<td><%= simple_time(u.created_at) %></td>
				<% if current_user.admin? %>
					<td>
						<% if !current_user?(u) %>
							<%= link_to "削除", u, method: :delete, data: { confirm: "いいのか？" } %>
						<% end %>
					</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
<% end %>

<%= javascript_pack_tag 'users_view' %>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー登録') %>
<% provide(:url, signup_path) %>
<% provide(:button_text, '登録') %>
<h1>ユーザー登録</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>

<table class="table">
	<tr>
		<th class="col-xs-2">合計得点</th>
		<td class="col-xs-2"><%= @user.point %></td>
	</tr><tr>
		<th>解いた問題数</th>
		<td><%= @user.solved %></td>
	</tr><tr>
		<th>提出回数</th>
		<td><%= @user.submitted %></td>
	</tr><tr>
		<th>登録日時</th>
		<td><%= simple_time(@user.created_at) %></td>
	</tr>
</table>