config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
	get		'results/create'
	root	'static_pages#home'
	get		'/help',	to:	'static_pages#help'
	get		'/about',	to:	'static_pages#about'
	get		'/contact',	to:	'static_pages#contact'
	get		'/signup',	to:	'users#new'
	post	'/signup',	to:	'users#create'
	get		'/login',	to:	'sessions#new'
	post	'/login',	to:	'sessions#create'
	delete	'/logout',	to:	'sessions#destroy'
	post	'/result',	to:	'results#create'
	post	'/judged',	to:	'submissions#update'
	get		'submissions/renew',	to:	'submissions#renew'
	get		'submissions/srenew',	to:	'submissions#srenew'
	get		'submissions/getall',	to:	'submissions#getall'
	get		'problems/getnames',	to:	'problems#getnames'
	get		'users/getnames',		to:	'users#getnames'
	get		'users/getall',			to:	'users#getall'
	get		'problems/getall',		to:	'problems#getall'
	mathjax 'mathjax'
	resources :users
	resources :problems
	resources :submissions
	mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to "このサイトについて", about_path %></li>
			<li><%= link_to "ヘルプ", help_path %></li>
			<li><%= link_to "お問い合わせ", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "わくわくジャッジ", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "問題", problems_path %></li>
				<li><%= link_to "提出一覧", submissions_path %></li>
				<% if logged_in? %>
					<li><%= link_to "ランキング", users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							アカウント <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "プロフィール", current_user %></li>
							<li><%= link_to "設定", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "ログアウト", logout_path, method: :delete %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "ログイン", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= render 'layouts/rails_default' %>
		<%= render 'layouts/shim' %>
		<%= favicon_link_tag('favicon.ico') %>
		<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>